language: go

script:
    - go test -short ./...
    - go test ./... -run RandomizeFast -count=500
    - go test ./... -run RandomizeSlow -count=10

go_import_path: golang.org/x/crypto

go:
    - 1.10.x
    - 1.11.x
    - master
